### PR TITLE
 Check for required fields in XML Batch import

### LINKED ISSUE #634: BATCH IMPORT: Malformatted import files should give the user an error
When I supply an import file with the following issues, the application should alert the user and a batch should not be created.

- [x] Mismatched tags
- [x] Missing required fields (title, displays_in)
- [x] Missing structural nodes

For new object imports
- [x] each record has at least one filename
- [x] no filenames are duplicated

- [x] Ensure all sample data we provide in the documentation contains required fields

### LINKED ISSUE #716: BATCH IMPORT: all detectable errors should be listed when validating import file
**STORY**
As a librarian submitting a batch ingest manifest, I would like to see all detectible errors in my file, so that I can fix them at one time, instead of having to repeatedly resubmit my file to have additional errors listed.

**CURRENT BEHAVIOR**
Given the sample file below, I get the single error "Errors were found in display_default_import.xml: A file was missing for the record at line: Unknown Line;"

**EXPECTED BEHAVIOR**
I would like the import to tell me that it can't find an object type, filename, displays, and required title.

**ACCEPTANCE**
- [x] List all missing fields for each record.
- [x] if there are more than one record with error, list only the first record with an error and list "*X* additional records have errors detected."  e.g. for the sample file below, I should get the error text "1 additional record have errors detected."

**SAMPLE IMPORT FILE WITH MISSING FIELDS**
```
<?xml version="1.0"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/">
  <ListRecords>
    <record>
      <metadata>
        <mira_import xmlns:model="info:fedora/fedora-system:def/model#" xmlns:dc="http://purl.org/dc/terms/" xmlns:bibframe="http://bibframe.org/vocab/" xmlns:dc11="http://purl.org/dc/elements/1.1/" xmlns:ebucore="http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#" xmlns:premis="http://www.loc.gov/premis/rdf/v1#" xmlns:mads="http://www.loc.gov/mads/rdf/v1#" xmlns:marcrelators="http://id.loc.gov/vocabulary/relators/" xmlns:tufts="http://dl.tufts.edu/terms#" xmlns:scholarsphere="http://scholarsphere.psu.edu/ns#" xmlns:edm="http://www.europeana.eu/schemas/edm/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
        </mira_import>
      </metadata>
    </record>
    <record>
      <metadata>
        <mira_import xmlns:model="info:fedora/fedora-system:def/model#" xmlns:dc="http://purl.org/dc/terms/" xmlns:bibframe="http://bibframe.org/vocab/" xmlns:dc11="http://purl.org/dc/elements/1.1/" xmlns:ebucore="http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#" xmlns:premis="http://www.loc.gov/premis/rdf/v1#" xmlns:mads="http://www.loc.gov/mads/rdf/v1#" xmlns:marcrelators="http://id.loc.gov/vocabulary/relators/" xmlns:tufts="http://dl.tufts.edu/terms#" xmlns:scholarsphere="http://scholarsphere.psu.edu/ns#" xmlns:edm="http://www.europeana.eu/schemas/edm/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
            <tufts:filename>AK-Page-4.pdf</tufts:filename>
            <tufts:visibility>open</tufts:visibility>
            <model:hasModel>Pdf</model:hasModel>
        </mira_import>
      </metadata>
    </record>
  </ListRecords>
</OAI-PMH>
```

**SAMPLE CONTENT FILE - AK-Page-4**
https://github.com/curationexperts/camper/blob/master/sample-assets/AK-Page-4.pdf

### LINKED ISSUE #717: BATCH IMPORT: missing field errors should display the line number for the start of the record
**STEPS TO REPRODUCE**
Attempt to ingest the sample file below.

**EXISTING BEHAVIOR**
>Errors were found in sample_import.xml: A file was missing for the record at line: Unknown Line;

**EXPECTED BEHAVIOR**
>Errors were found in sample_import.xml: A file was missing for the record at line: 14

**ACCEPTANCE**
- [x] The flash message shows the line number where the record node starts.  e.g. for the sample below, is should display "Line #14"

**SAMPLE**
```
<?xml version="1.0"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/">
  <ListRecords>
    <record>
      <metadata>
        <mira_import xmlns:model="info:fedora/fedora-system:def/model#" xmlns:dc="http://purl.org/dc/terms/" xmlns:bibframe="http://bibframe.org/vocab/" xmlns:dc11="http://purl.org/dc/elements/1.1/" xmlns:ebucore="http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#" xmlns:premis="http://www.loc.gov/premis/rdf/v1#" xmlns:mads="http://www.loc.gov/mads/rdf/v1#" xmlns:marcrelators="http://id.loc.gov/vocabulary/relators/" xmlns:tufts="http://dl.tufts.edu/terms#" xmlns:scholarsphere="http://scholarsphere.psu.edu/ns#" xmlns:edm="http://www.europeana.eu/schemas/edm/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
            <tufts:filename>AK-Page-4.pdf</tufts:filename>
            <tufts:visibility>open</tufts:visibility>
            <model:hasModel>Pdf</model:hasModel>
			<tufts:displays_in>nowhere</tufts:displays_in>
        </mira_import>
      </metadata>
    </record>
    <record>
      <metadata>
        <mira_import xmlns:model="info:fedora/fedora-system:def/model#" xmlns:dc="http://purl.org/dc/terms/" xmlns:bibframe="http://bibframe.org/vocab/" xmlns:dc11="http://purl.org/dc/elements/1.1/" xmlns:ebucore="http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#" xmlns:premis="http://www.loc.gov/premis/rdf/v1#" xmlns:mads="http://www.loc.gov/mads/rdf/v1#" xmlns:marcrelators="http://id.loc.gov/vocabulary/relators/" xmlns:tufts="http://dl.tufts.edu/terms#" xmlns:scholarsphere="http://scholarsphere.psu.edu/ns#" xmlns:edm="http://www.europeana.eu/schemas/edm/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
        </mira_import>
      </metadata>
    </record>
  </ListRecords>
</OAI-PMH>
````

### LINKED ISSUE #741: BATCH IMPORT: Cookie overflow error for very badly malformed XML
When I upload a very badly malformed XML file to batch upload, the application throws a cookie overload error, presumably because there are so many errors

### PR DESCRIPTION
**Pull request by bess**
1. Move the XML validation check to the validate! method

2. When there are XML validation errors only report the
first one. A single stray element causes six errors because
it cascades -- really, the user just needs to know the
document is malformed and they should go check it with
an XML parser.

3. Add a method to validate! that checks for required fields.
Right now this includes "dc:title", "tufts:displays_in",
and "model:hasModel". Eventually we might want to put this in
a config somewhere.

4. Explicitly add namespaces of the required fields we're
checking for to the in-memory XML document. The way we
declare XML namespaces varies across some of the test files
we're using, and this ensures the validation works across
that variation.

5. Add required displays_in element to sample import files

6. Only display the first five validation error messages, but include 
the total number of errors.

7. Add the line number to missing filename errors

Fixes #634 
Fixes #741 
Fixes #716 
Fixes #717

### CODE REVIEW

File: app/lib/tufts/importer.rb [hunk 1]
```diff
@@ -152,17 +150,34 @@ def message
...
+        if doc.errors.count > 0
+          e = doc.errors.first
+          errors << Importer::Error.new(e.line, type: :serious, message: "Malformed XML error: #{e.message}")
+        end
+        check_for_required_fields(doc)
+      end
+
+      # Given a record, check that it has all required fields
+      def check_for_required_fields(doc)
+        doc.root.add_namespace("dc", "http://purl.org/dc/terms/")
```
Comment (no-reply) [inline app/lib/tufts/importer.rb]: Can you say something about the need to add the namespaces explicitly? Would it be better to pull the namespaces from the MiraXmlMapping?

File: spec/fixtures/files/mira_xml.xml [hunk 2]
```diff
@@ -21,15 +21,16 @@ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
...
           <model:hasModel>Pdf</model:hasModel>
           <dc:title>President Jean Mayer speaking
           at commencement, 1987</dc:title>
           <dc11:description>
-            A long       description             with 
+            A long       description             with
                            plenty
           of          whitespace</dc11:description>
           <dc:abstract>
-            Another long       description             with
```
Comment (no-reply) [inline spec/fixtures/files/mira_xml.xml]: I think this file is intended to have trailing whitespace, and the corresponding test in spec/lib/tufts/import_record_spec.rb, is meant to explicitly test that it is retained.

I know this is a pain, but I think we need to keep it. https://twitter.com/no_reply/status/940737286446051329
