### PR TITLE
Avoid re-enequing XmlImport items that have already been enqueued

### LINKED ISSUE #680: BATCH IMPORT: Some objects are failing to import
A significant number of objects (51 in the past hour) are failing to import because they are encountering an exception, namely:

[epigaea/production] ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'gid://epigaea/GenericObject/3b591857h' for key 'sipity_entities_proxy_for_global_id': INSERT INTO `sipity_entities` (`proxy_for_global_id`, `workflow_id`, `created_at`, `updated_at`) VALUES ('gid://epigaea/GenericObject/3b591857h', 1, '2017-12-07 17:31:31', '2017-12-07 17:31:31')

## Backtrace

    line 58 of [PROJECT_ROOT]/app/services/tufts/import_service.rb: import_object!
    line 29 of [PROJECT_ROOT]/app/services/tufts/import_service.rb: import_object!
    line 6 of [PROJECT_ROOT]/app/jobs/import_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54127/faults/35762931)

### PR DESCRIPTION
**Pull request by no-reply**
Items that have been or are set to be processed by other jobs could prevously be
re-uploaded, triggering an additional job for the same item. That job would
become stuck in queue, as it failed repeatedly to create an item that already
exists. This avoids the requeue.

A small performance refactor of `Batch::Item` is also included here, to avoid
unneeded Fedora calls while checking for job ids.

Fixes #680.

### CODE REVIEW

File: app/models/batch.rb [hunk 1]
```diff
@@ -51,9 +51,10 @@ class Item
     #   @return [String]
     # @!attribute id [rw]
     #   @return [String]
-    # @!attribute object [rw]
-    #   @return [ActiveFedora::Base, String]
+    # @!attribute object [w
+    #   @return [ActiveFedora::Base, nil]
     attr_accessor :batch_id, :id, :object, :store
+    attr_writer   :object
```
Comment (mark-dce) [inline app/models/batch.rb]: I'm don't quite get why :object appears in both 56 and 57 - doesn't :object in line 56 imply there's both reader and writer (for all of the attributes in 56)?

File: app/models/batch.rb [hunk 2]
```diff
@@ -51,9 +51,10 @@ class Item
     #   @return [String]
     # @!attribute id [rw]
     #   @return [String]
-    # @!attribute object [rw]
-    #   @return [ActiveFedora::Base, String]
+    # @!attribute object [w
```
[the remark this answers is not in the document]
Comment (no-reply) [reply app/models/batch.rb]: yes, thanks. Will fix.

File: app/models/batch.rb (hunk 1 above)
Comment (no-reply) [reply app/models/batch.rb]: it should have been removed from accessors, thanks!
