### PR TITLE
Fix draft persisting after save

### LINKED ISSUE #410: Draft persists after saving the work
When you save the work, an existing draft should be deleted.

### PR DESCRIPTION
**Pull request by little9**
Closes #410

### CODE REVIEW

File: spec/features/create_draft_spec.rb [hunk 1]
```diff
@@ -31,6 +31,14 @@
       expect(page).to have_content('edited')
       click_on 'Revert Draft'
       expect(page).to have_content('published')
+      # Test to see if the draft has been deleted after saving the work
+      click_on 'Save Draft'
```
Comment (no-reply) [inline spec/features/create_draft_spec.rb]: I'm not sure I'm following the order of the test setup. After `Revert`, it seems like we want to `fill_in` *before* saving another draft. Am I missing something?

Comment (little9) [reply spec/features/create_draft_spec.rb]: This feature test isn't testing the actual values of the draft, so you don't necessarily need to have changes on that second 'Save Draft'. I added the `fill_in` 's below this because Capybara was going through the process too quickly to pass.

Comment (no-reply) [reply spec/features/create_draft_spec.rb]: ha! Okay. That feels slightly hacky, but I'm happy to let it pass for now.
