### PR TITLE
Ensure capistrano restarts consistently after deploy

### LINKED ISSUE #670: Footer version isn't updating without apache restart
**STEPS TO REPRODUCE**
1. Check the footer
1. Deploy a different branch
1. Check the footer

**EXPECTED RESULT**
The footer should display the newly deployed branch and date

**ACTUAL RESULT**
The footer appears to remain unchanged

Check out the Branch listed by the deployment vs. the first curl vs. the curl after restarting apache
```
# last line fo the deployment
00:41 deploy:log_revision
      01 echo "Branch v2017.12.07.beta (at 622d51617c551c783160a630cbc456073391aba5) deployed as release 20171207085443 by mark" >> /opt/epi…
    ✔ 01 deploy@epigaea.curationexperts.com 0.064s

Marks-MacBook-Pro:epigaea mark$ curl http://epigaea.curationexperts.com | grep Version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5854    0  5854    0     0  24845      0 --:--:-- --:--:-- --:--:-- 24910
      Version <span title="b4398183b90daf3c221d3bc01f35c94a484bf53d">master updated 05 December 2017</span>

Marks-MacBook-Pro:epigaea mark$ ssh epigaea.curationexperts.com
. . .
mark@epigaea:~$ sudo service apache2 restart
mark@epigaea:~$ exit
logout
Connection to epigaea.curationexperts.com closed.

Marks-MacBook-Pro:epigaea mark$ curl http://epigaea.curationexperts.com | grep Version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5864    0  5864    0     0    846      0 --:--:--  0:00:06 --:--:--  1244
      Version <span title="622d51617c551c783160a630cbc456073391aba5">v2017.12.07.beta updated 07 December 2017</span>
Marks-MacBook-Pro:epigaea mark$ 
```

### PR DESCRIPTION
**Pull request by bess**
Add delay to passenger restart
Add time of deploy to footer for easier debugging

Fixes #670 

With the `:passenger_restart_wait` option added I was able to deploy over and over again and see the deployed footer each time, using curl:

```
      Version <span title="45163a30696a84e452bde5242c6deabf40405bc2">restart_on_cap_deploy updated  7 Dec 2017 16:02:05</span>
      Version <span title="45163a30696a84e452bde5242c6deabf40405bc2">restart_on_cap_deploy updated  7 Dec 2017 16:02:57</span>
      Version <span title="45163a30696a84e452bde5242c6deabf40405bc2">restart_on_cap_deploy updated  7 Dec 2017 16:03:59</span>
      Version <span title="45163a30696a84e452bde5242c6deabf40405bc2">restart_on_cap_deploy updated  7 Dec 2017 16:05:01</span>
```

### CODE REVIEW

File: config/initializers/git_sha.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@
 LAST_DEPLOYED =
   if Rails.env.production? && File.exist?('/opt/epigaea/revisions.log')
     deployed = `tail -1 /opt/epigaea/revisions.log`.chomp.split(" ")[7]
-    Date.parse(deployed).strftime("%d %B %Y")
+    DateTime.parse(deployed).strftime("%e %b %Y %H:%M:%S") # rubocop:disable Rails/TimeZone
```
Comment (val99erie) [inline config/initializers/git_sha.rb]: Can you put the rubocop exception into the `.rubocop.yml` file instead of in the source code.  I feel like sprinkling rubocop rules all over the code will needlessly clutter up the code.

**Comment by bess** [comment]
@val99erie rubocop exception moved, as requested
