### PR TITLE
Fix the default Hyrax batch create work forms

### LINKED ISSUE #641: BATCH IMPORT: Create Batch of works button fails
**STEPS TO REPRODUCE**
1. Login as an administrator
1. Go to the admin dashboard
1. Click on the "Works" link in the left
1. Click on "Create batch of works" button
1. Select "Audio" and click on "Create Work"

**EXPECTED BEHAVIOR**
I should probably be take to the new object import page when I click "Create batch of works"

**ACTUAL BEHAVIOR**
I get an error

### PR DESCRIPTION
**Pull request by little9**
This commit fixes the batch create work forms by setting the
`Hyrax::Forms::BatchUploadForm.terms` variable to the terms
that we use in forms via an initializer. The `_form_metadata` partial
has also been tweaked so that it displays properly on the batch
create work pages.

This is tested  with a feature spec that adds a `Pdf` work via the
batch upload form.

This removes the `_form_metadata` view specs and shared examples in favor of checking for the transcript UI in the Audio / Video feature specs and checking that the transcript UI doesn't show up in the create Pdf feature spec. The create Pdf / Audio / Video feature specs are already being run and this replaces the 40+ lines of view specs with 3 lines of additional expectations in the feature specs.

I think that it is important to keep the default Hyrax batch new work features working.

Fixes #641

### CODE REVIEW

File: spec/features/create_video_spec.rb [hunk 1]
```diff
@@ -20,6 +20,8 @@
         click_button "Create work"
       end
       expect(page).to have_content "Add New Video"
+      # We want the transcription UI to show up on the form
+      expect(page).to have_content('You will need to attach an XML file to to this work to select a transcript.')
```
Comment (little9) [inline spec/features/create_video_spec.rb]: @no-reply  this replaces the view spec for video

**Comment by no-reply** [comment]
@little9 thanks for the squash, and for indulging the review.

Can you clarify for me why the view specs (which had been working before), stop working with this PR? I'm not sure I agree that deleting them and treating it as covered by the feature spec is good, but if we understand why they are failing and they are a pain to fix, then I'm fine with it.

I'd also like to get @mark-dce's :+1: that this does in fact fix #641.

File: spec/features/create_pdf_spec.rb [hunk 2]
```diff
@@ -22,6 +22,8 @@
       # Hyrax::BasicMetadata attributes that we don't want in the form
       expect(page).to have_no_content('Keywords')
       expect(page).to have_no_content('Location')
+      # We don't want the transcript UI to show up on the Pdf form
+      expect(page).not_to have_content('You will need to attach an XML file to to this work to select a transcript.')
```
Comment (little9) [inline spec/features/create_pdf_spec.rb]: @no-reply this replaces the view spec for forms that shouldn't have the transcript UI

File: config/initializers/batch_form_terms.rb [hunk 3]
```diff
@@ -0,0 +1,4 @@
+# This sets up the correct terms for the batch works forms
```
Comment (no-reply) [inline config/initializers/batch_form_terms.rb]: I'm guessing setting these in an initializer is a Hyrax convention?

File: app/views/hyrax/base/_form_metadata.html.erb [hunk 4]
```diff
@@ -1,13 +1,16 @@
...
-    <%= render_edit_field_partial(:transcript_id, f: f) %>
-  </div>
+    <div class="well transcript-selection">
+        <%= render_edit_field_partial(:transcript_id, f: f) %>
+    </div>
 <% end %>
 
 <div class='base-terms'>
-<%= render_edit_field_partial(:title,  f: f) %>
+<% unless current_page?(:controller => 'batch_uploads', :action => 'new') %>
```
Comment (little9) [inline app/views/hyrax/base/_form_metadata.html.erb]: This doesn't work in the existing view specs because (I may not be phrasing this correctly) the controller isn't available in that kind of test.

File: config/initializers/batch_form_terms.rb (hunk 3 above)
Comment (little9) [reply config/initializers/batch_form_terms.rb]: Dunno, I'm not sure how else you would setup the correct terms for that form. 

https://github.com/samvera/hyrax/blob/master/app/forms/hyrax/forms/batch_upload_form.rb

inherits from from work_form which has a set of terms that we don't want:

https://github.com/samvera/hyrax/blob/master/app/forms/hyrax/forms/work_form.rb#L24

File: app/views/hyrax/base/_form_metadata.html.erb (hunk 4 above)
Comment (no-reply) [reply app/views/hyrax/base/_form_metadata.html.erb]: It looks like `rspec/rails` folks recommend stubbing the helper: https://github.com/rspec/rspec-rails/issues/1347

Could we do that and keep the tests? It seems like a waste to have spent the time writing them and then just delete them because there's churn in the view.

**Comment by no-reply** [comment]
Re:

> I'd also like to get @mark-dce's :+1: that this does in fact fix #641.

I'm also fine merging this as an improvement and assigning #641 to @mark-dce for acceptance.

File: app/views/hyrax/base/_form_metadata.html.erb (hunk 4 above)
Comment (no-reply) [reply app/views/hyrax/base/_form_metadata.html.erb]: The issue seems to be that this is a partial test: https://relishapp.com/rspec/rspec-rails/docs/view-specs/view-spec-infers-controller-path-and-action#do-not-infer-action-in-a-partial

Comment (little9) [reply app/views/hyrax/base/_form_metadata.html.erb]: Hmm should I move them into a different folder?
